/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPlacePhotoRouteImport } from './routes/api/public/place-photo'
import { Route as ApiPublicPlacesEnrichmentRouteImport } from './routes/api/public/places-enrichment'
import { Route as ApiPublicRoadRouteRouteImport } from './routes/api/public/road-route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlacePhotoRoute = ApiPublicPlacePhotoRouteImport.update({
  id: '/api/public/place-photo',
  path: '/api/public/place-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlacesEnrichmentRoute =
  ApiPublicPlacesEnrichmentRouteImport.update({
    id: '/api/public/places-enrichment',
    path: '/api/public/places-enrichment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRoadRouteRoute = ApiPublicRoadRouteRouteImport.update({
  id: '/api/public/road-route',
  path: '/api/public/road-route',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/place-photo': typeof ApiPublicPlacePhotoRoute
  '/api/public/places-enrichment': typeof ApiPublicPlacesEnrichmentRoute
  '/api/public/road-route': typeof ApiPublicRoadRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/place-photo': typeof ApiPublicPlacePhotoRoute
  '/api/public/places-enrichment': typeof ApiPublicPlacesEnrichmentRoute
  '/api/public/road-route': typeof ApiPublicRoadRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/place-photo': typeof ApiPublicPlacePhotoRoute
  '/api/public/places-enrichment': typeof ApiPublicPlacesEnrichmentRoute
  '/api/public/road-route': typeof ApiPublicRoadRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/place-photo'
    | '/api/public/places-enrichment'
    | '/api/public/road-route'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/place-photo'
    | '/api/public/places-enrichment'
    | '/api/public/road-route'
  id:
    | '__root__'
    | '/'
    | '/api/public/place-photo'
    | '/api/public/places-enrichment'
    | '/api/public/road-route'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicPlacePhotoRoute: typeof ApiPublicPlacePhotoRoute
  ApiPublicPlacesEnrichmentRoute: typeof ApiPublicPlacesEnrichmentRoute
  ApiPublicRoadRouteRoute: typeof ApiPublicRoadRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/place-photo': {
      id: '/api/public/place-photo'
      path: '/api/public/place-photo'
      fullPath: '/api/public/place-photo'
      preLoaderRoute: typeof ApiPublicPlacePhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/places-enrichment': {
      id: '/api/public/places-enrichment'
      path: '/api/public/places-enrichment'
      fullPath: '/api/public/places-enrichment'
      preLoaderRoute: typeof ApiPublicPlacesEnrichmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/road-route': {
      id: '/api/public/road-route'
      path: '/api/public/road-route'
      fullPath: '/api/public/road-route'
      preLoaderRoute: typeof ApiPublicRoadRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicPlacePhotoRoute: ApiPublicPlacePhotoRoute,
  ApiPublicPlacesEnrichmentRoute: ApiPublicPlacesEnrichmentRoute,
  ApiPublicRoadRouteRoute: ApiPublicRoadRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
